apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nqo0xal1h-go
  janus-idp.io/tekton: nqo0xal1h-go
  backstage.io/kubernetes-id: nqo0xal1h-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nqo0xal1h-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
