apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nqo0xal1h-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nqo0xal1h-go 
  name: nqo0xal1h-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nqo0xal1h-go 
